### ISSUE TITLE
addalpha() support

### ISSUE THREAD

**Issue by RiskoZS** [jcupitt/lua-vips#47]
The VIPS docs [mention an `addalpha()` function](https://www.libvips.org/API/current/libvips-conversion.html#vips-addalpha), but attempting to call `image:addalpha()` results in a `VipsOperation: class "addalpha" not found` error. I'm not sure why exactly this is. It's mentioned here that [`addalpha` is just a convenience function for `bandjoin_const`](https://github.com/libvips/libvips/issues/1449#issuecomment-554945494), but I don't see what makes it different from any other operation that the binding supports.

I'd open a PR, but thing is, I'm not sure how to implement it. Typically, I'd just make a call to `vips_lib.vips_addalpha()`, but [pyvips defines the function manually](https://github.com/libvips/pyvips/blob/a6d622957743f6f015a51e6b80fdbeccc85b44ae/pyvips/vimage.py#L1433), so there might be something I'm missing.

**Comment by jcupitt** [comment]
Hi @RiskoZoSlovenska,

Most libvips operations are defined as subclasses of VipsOperation, and they all just appear in lua-vips automatically. A few very simple things (eg. addalpha, which is just two lines of code) are tiny convenience functions and are implemented in the bindings themselves.

I'd implement addalpha in lua in `Image_methods.lua`, which I guess is what you've done in your PR. I'll have a look.
