### ISSUE TITLE
cannot load module 'libvips-42.dll' on Windows

### ISSUE THREAD

**Issue by gVimer** [jcupitt/lua-vips#54]
![image](https://github.com/libvips/lua-vips/assets/6241431/10c33ad4-77a1-4863-b2b7-21ef9b217b46)
![image](https://github.com/libvips/lua-vips/assets/6241431/73b0c7a0-dce5-44e6-9a7c-e7ecd8e47b78)
add the bin area of the libvips Windows build to PATH.Can you help me?

**Comment by jcupitt** [comment]
Hi, 

I think you can use `os.setenv("PATH", ...)` in your code before starting FFI. Though I've not tested it.

**Comment by gVimer** [comment]
Thank you for your replay but there is no the method in os module
![image](https://github.com/libvips/lua-vips/assets/6241431/156943ad-a37a-402a-9b57-2a6641f2f6a5)
![image](https://github.com/libvips/lua-vips/assets/6241431/568210b9-9c6b-42d4-abe6-7626728d3dbb)
I can use the VIPs command,This can indicate that I have set the environment variables correctly.
![image](https://github.com/libvips/lua-vips/assets/6241431/51965807-1168-4e0d-b2a5-d58ebab6fe6a)

**Comment by gVimer** [comment]
It still reported an error when using an absolute path to load
![image](https://github.com/libvips/lua-vips/assets/6241431/e8ad5673-6af2-4ed4-ae3a-d7e1222055dc)

**Comment by jcupitt** [comment]
Then it'll probably be one of the classic Windows linking issues. Either you're trying to mix 32- and 64-bit code, or you have a DLL clash on your path.

Look at your path carefully and make sure you only have one version of each DLL on the PATH variable.

**Comment by gVimer** [comment]
Thank you for your help and I Successfully solved this problem.
Just let the Vips dll to be the first search path.
![image](https://github.com/libvips/lua-vips/assets/6241431/813f8661-aedd-4930-a108-3430a5f868c8)

**Comment by jcupitt** [comment]
Unfortunately this has probably broken some other software you have installed :( 

The libvips BIN area includes a lot of common DLLs, such as libjpeg. If you have another package installed which also includes libjpeg.dll, and that older libjpeg.dll is not binary compatible with the one that libvips ships, that other package will no longer work.

It's safest not to change PATH, and instead set PATH in your program during startup. 

Perhaps with https://stackoverflow.com/questions/41367667/set-shell-environment-variable-in-a-lua-5-3-script ?

**Comment by gVimer** [comment]
Ok,Thank you for your suggestion. I will try it out.
