### ISSUE TITLE
Text only renders with font file that was loaded first

### ISSUE THREAD

**Issue by piface314** [jcupitt/lua-vips#58]
I have multiple .ttf fonts in different file paths, and in my application, if I try to create two text images with different font files, only the first one is properly rendered with the font.

For instance, running the code:

    vips.Image.text("TEST1", {font = "Stone Serif 10", fontfile = "stone-serif.ttf", dpi = 300}):write_to_file("test1.png")
    vips.Image.text("TEST2", {font = "MatrixBoldSmallCaps 10", fontfile = "matrix.ttf", dpi = 300}):write_to_file("test2.png")

produces:

![test1](https://github.com/libvips/lua-vips/assets/22157025/ac07f0ec-7886-4503-9055-0455c9f33403)
![test2](https://github.com/libvips/lua-vips/assets/22157025/a4f1a702-5ce3-41ea-914d-be78bb58fd29)

If I swap the lines, I get a different result:

![test1](https://github.com/libvips/lua-vips/assets/22157025/cd3baad1-2ca3-4379-b49d-95b902e097aa)
![test2](https://github.com/libvips/lua-vips/assets/22157025/62d57a2f-ff1d-4450-9312-0b224b4efb19)

What could be the reason behind this?

**vips version:** 8.12.1

**Comment by jcupitt** [comment]
Hi @piface314,

There have been a few fixes to font handling since 8.12 (three years ago). I would update your libvips.

I tried with current stable:

```lua
#!/usr/bin/luajit

vips = require "vips"

local image = vips.Image.text("TEST1", {
    font = "MissFajardose 10", 
    fontfile = "/home/john/pics/MissFajardose-Regular.ttf",
    dpi = 600
})
image:write_to_file("test1.png")

image = vips.Image.text("TEST2", {
    font = "PT Serif, Bold 10",
    fontfile = "/home/john/pics/PT_Serif-Web-Bold.ttf",            
    dpi = 600
})
image:write_to_file("test2.png")
```

To make:

![test1](https://github.com/libvips/lua-vips/assets/580843/85e5034f-190d-4ee6-9981-84d8d3c6dea1)
![test2](https://github.com/libvips/lua-vips/assets/580843/9a9eb1b8-b1c5-4fc1-90d5-e61ce9e74409)

I get the same result if I swap the two text render operations.

**Comment by piface314** [comment]
Oh, I see. I was using this version because it seems to be the newest version available on `apt`. In this case, should I build from source?

**Comment by jcupitt** [comment]
Yes, or update your OS, of course. There are various libvips PPAs as well.

**Comment by piface314** [comment]
Thanks! I found a PPA with a more recent version and it solved the problem.
