### ISSUE TITLE
Methods `thumbnail` and `thumbnail_buffer` do not exist

### ISSUE THREAD

**Issue by monochromer** [jcupitt/lua-vips#87]
I want to use "lua-vips" (version 8.4.5) via "OpenResty" to resize images, but when call methods `thumbnail` and `thumbnail_buffer`, i get error:

```lua
local vips = require "vips"
local image = vips.Image.thumbnail(image_path, 400);
--- or
local image = vips.Image.thumbnail_buffer(image_buffer);
```

```
lua entry thread aborted: runtime error: 
...local/openresty/luajit/share/lua/5.1/vips/voperation.lua:150: no such operation

VipsOperation: class "thumbnail_buffer" not found
```

This methods are available? Or i'm doing something wrong? Maybe exist another method to resize image via lua bindings?

**Comment by jcupitt** [comment]
Hello @monochromer,

lua-vips uses FFI to open the libvips shared library, and then presents the operations it finds in there.

If it can't find an operation, it's usually either because the shared library is missing, or out of date. Are you sure you have `libvips.so` installed? Do you know what version?

**Comment by monochromer** [comment]
> Do you know what version?

I'm not shure. I install with this commands:

```
apt-get remove libvips42 \
  && apt update \
  && apt install -y libvips libvips-tools libvips-dev
```

But there is message:
```
Note, selecting 'libvips42' instead of 'libvips'
libvips42 is already the newest version (8.4.5-1build1).
```

P.S. I used docker image `openresty/openresty:bionic` (Ubuntu Bionic)

**Comment by monochromer** [comment]
Ok, this is old distributive and old packages
