### ISSUE TITLE
No known route from 'multiband' to 'srgb' when using composite operation

### ISSUE THREAD

**Issue by Seanxyc** [jcupitt/lua-vips#91]
## Description
When trying to use `composite` operation in lua-vips, I'm getting an error about color space conversion: "no known route from 'multiband' to 'srgb'". This same operation works fine in pyvips.

## Minimal Example
Here's a comparison between working pyvips code and problematic lua-vips code:

### Working Python code (pyvips):
```
shadow_alpha = image[-1]
shadow_rgb = shadow_alpha.new_from_image([100, 100, 100])
shadow = shadow_rgb.bandjoin(shadow_alpha)
background = shadow.new_from_image([255, 255, 255])
final = background.composite([shadow, image], "over",
x=[offset1, offset2],
y=[offset1, offset2])
```
### Problematic Lua code (lua-vips):
```
local shadow_alpha = img:extract_band(img:bands() - 1)
local shadow_rgb = shadow_alpha:new_from_image({100, 100, 100})
local shadow = shadow_rgb:bandjoin(shadow_alpha)
local background = shadow:new_from_image({255, 255, 255})
local result = background:composite({shadow, img}, "over", {
x = {offset1, offset2},
y = {offset1, offset2}
})
```

## Error Message
Image core functions border effects should add shadow with custom dimensions
/opt/homebrew/share/lua/5.4/vips/voperation.lua:239: unable to call composite
vips_colourspace: no known route from 'multiband' to 'srgb'

## Expected Behavior
The lua-vips code should work the same way as the pyvips code, automatically handling color space conversion when using `composite` operation.

## Question
Is this a known limitation in lua-vips? Or is there a different way to handle color space conversion in lua-vips compared to pyvips?

**Comment by rolandlo** [comment]
Using a sample png image with some transparency the Lua code worked just fine (tested with Lua 5.3, lua-vips 1.1-11 and libvips 8.16). Can you share an image where it doesn't work?

**Comment by jcupitt** [comment]
The annoying "no known route" message was quite common with libvips 8.12 (I think?), but should be very rare with current libvips.

Perhaps your lua-vips install is picking up an older libvips version?

**Comment by Seanxyc** [comment]
I apologize for the false alarm. The issue was with my auto-generated test image using `vips.Image.black()`. When using real image files (JPG/PNG), everything works as expected.

Thanks for your help. Closing this issue.
